### ISSUE TITLE
Example in a separate branch makes it really hard to develop the dropdown

### ISSUE THREAD

**Issue by marcysutton** [Fauntleroy/react-simple-dropdown#19]
Maybe I'm missing something, but having your example code in `gh-pages` and pointing to the npm module as source code makes it really hard to contribute back to the dropdown. I was hoping to work on the accessibility of this dropdown and I'm finding it impossible to work with. Having a working example you can run in a local server would make it a lot easier to contribute back to this component.

**Comment by Fauntleroy** [comment]
Hey Marcy, thanks for submitting your issue!

I've always had hella trouble with running the example as well, for the same reason. Ultimately it's because I was using the example for the `gh-pages` site, so I'd have to switch branches all the time and... ech.

LUCKILY, GitHub just released a (new `gh-pages` feature)[https://github.com/blog/2228-simpler-github-pages-publishing] which will make things way easier. I'll work on implementing that soon!

**Comment by Fauntleroy** [comment]
Hey @marcysutton, I just took care of this issue in `master`. Please try it out and tell me if it works for you!
