### ISSUE TITLE
Deprecation warnings for use of React.PropTypes and React.createClass

### ISSUE THREAD

**Issue by brynjagr** [Fauntleroy/react-simple-dropdown#33]
As of React v15.5.0 you get deprecation warnings for using `React.PropTypes` and `React.createClass`. You now have to import these from separate packages (https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

Edit: Also, react-addons-test-utils has been moved to react-dom/test-utils…

**Comment by andrevenancio** [comment]
I'm interested in this update too. However, based on the pending Pull Requests at this repo I assume the contributors aren't on top of this. Hope I'm wrong.

**Comment by Fauntleroy** [comment]
I am paying attention to this issue and researching the best way to move forward with this. `peerDependencies` are my current sticking point, and once I figure out what I'd like to do about that there will be a version increment and release.

@andrevenancio pull requests are always welcome!

**Comment by brynjagr** [comment]
I think both create-react-class and prop-types will work with previous versions of React. Including them as dependencies will of course make bundles a bit larger than necessary for people using React <v16 .

Another possibility would be switch to ES6 classes – then you would only need to add prop-types.

**Comment by andrevenancio** [comment]
They shouldn't make bundles larger. The reason PropTypes was removed from React was to make React bundle smaller because most people don't use it. *at least that was what they say on their website.

So in theory the code just changed to an external package.

I'm happy to do a PR, but I've noticed you had long pending PR's so assumed this wasn't being actively maintained. :)

**Comment by Fauntleroy** [comment]
@andrevenancio @brynjagr Could you try installing `react-simple-dropdown@3.0.0-alpha.1`?

**Comment by andrevenancio** [comment]
installed, and warnings disappear. All good for me

**Comment by bmv437** [comment]
Hey @Fauntleroy, when do you expect to release `3.0.0` out of alpha?
It was difficult to find this `3.0.0-alpha.1` release since it isn't listed on the [releases](https://github.com/Fauntleroy/react-simple-dropdown/releases) page, or on [npm](https://www.npmjs.com/package/react-simple-dropdown)

Thanks!

**Comment by Fauntleroy** [comment]
@bmv437 You should be able to find `3.0.0` on npm. The changelog can be found here: https://github.com/Fauntleroy/react-simple-dropdown/releases/tag/3.0.0

**Comment by bmv437** [comment]
@Fauntleroy Awesome, thank you for all your hard work!
